---
- name: Manage Sovereign NTP Service
  hosts: all
  become: yes
  tasks:
    - name: Ensure base software is present
      ansible.builtin.apt:
        name: chrony
        state: present

    - name: Manage the configuration file
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/chrony/chrony.conf
        mode: '0644'
        owner: root
      notify: Restart NTP service

  handlers:
    - name: Restart NTP service
      ansible.builtin.service:
        name: chrony
        state: restarted