#!/usr/bin/env python3
import sys
import os

if len(sys.argv) < 2:
    print("Usage: ./guardian <filename>")
    sys.exit(1)

filename = sys.argv[1]

if os.path.exists(filename):
    os.remove(filename)
    print(f"Success: {filename} has been deleted.")
    sys.exit(0)
else:
    sys.stderr.write(f"Error: {filename} not found!\n")
    sys.exit(1)
