---
inventory:
  plugin: NetBoxInventory2
  options:
    nb_url: "http://localhost:8000"
    nb_token: " nbt_893DVr8wXCL7.x1Pj1cpHtezKVLjm5YHU9upXJbdPk4Prxp9t0MPW"
    ssl_verify: false

runner:
  plugin: threaded
  options:
    num_workers: 20